In [27]:
import numpy as np
import pandas as pd
from scipy import stats

import plotly
import plotly.graph_objects as go

import statsmodels.api as sm
from statsmodels.stats.stattools import durbin_watson

In [28]:
df = pd.read_csv("./content/multiregress-092022.csv")
df

     i    ne   Me    tc      ge    CO2     NOx
0    1  1200  140  80.7  233.16   5.88  665.25
1    2  1200  210  82.8  225.23   8.67  900.50
2    3  1200  252  83.2  232.83  10.58  957.19
3    4  1400   28  79.3  478.57   3.11  199.84
4    5  1400   70  80.2  292.57   4.33  325.21
5    6  1400  140  80.7  236.49   6.50  610.04
6    7  1400  210  83.2  227.94   8.75  818.10
7    8  1400  252  83.7  237.09  10.90  836.57
8    9  1600   28  80.3  506.77   3.11  175.13
9   10  1600   70  80.4  300.99   4.33  303.89
10  11  1600  140  81.5  238.77   6.50  566.38
11  12  1600  210  82.3  229.92   9.09  795.66
12  13  1600  252  84.3  244.17  11.46  814.56
13  14  1800   28  80.2  537.04   3.30  170.97
14  15  1800   70  80.7  311.98   4.51  283.75
15  16  1800  140  82.1  248.01   6.77  526.49
16  17  1800  210  83.1  237.34   9.59  748.64
17  18  1800  252  85.0  258.16  12.02  730.34
18  19  2000   28  80.7  570.84   3.58  171.73
19  20  2000   70  80.8  239.71   4.88  280.93
20  21  2000  140  82.8  257.99   7.12  507.44
21  22  2000  210  83.6  247.54  10.01  683.83

In [29]:
df = df.drop("i", axis=1)
df

      ne   Me    tc      ge    CO2     NOx
0   1200  140  80.7  233.16   5.88  665.25
1   1200  210  82.8  225.23   8.67  900.50
2   1200  252  83.2  232.83  10.58  957.19
3   1400   28  79.3  478.57   3.11  199.84
4   1400   70  80.2  292.57   4.33  325.21
5   1400  140  80.7  236.49   6.50  610.04
6   1400  210  83.2  227.94   8.75  818.10
7   1400  252  83.7  237.09  10.90  836.57
8   1600   28  80.3  506.77   3.11  175.13
9   1600   70  80.4  300.99   4.33  303.89
10  1600  140  81.5  238.77   6.50  566.38
11  1600  210  82.3  229.92   9.09  795.66
12  1600  252  84.3  244.17  11.46  814.56
13  1800   28  80.2  537.04   3.30  170.97
14  1800   70  80.7  311.98   4.51  283.75
15  1800  140  82.1  248.01   6.77  526.49
16  1800  210  83.1  237.34   9.59  748.64
17  1800  252  85.0  258.16  12.02  730.34
18  2000   28  80.7  570.84   3.58  171.73
19  2000   70  80.8  239.71   4.88  280.93
20  2000  140  82.8  257.99   7.12  507.44
21  2000  210  83.6  247.54  10.01  683.83

In [30]:
df.corr(method="pearson")

           ne        Me        tc        ge       CO2       NOx
ne   1.000000 -0.254493  0.058692  0.245418 -0.127586 -0.424782
Me  -0.254493  1.000000  0.918038 -0.747814  0.984981  0.967156
tc   0.058692  0.918038  1.000000 -0.579430  0.957723  0.812078
ge   0.245418 -0.747814 -0.579430  1.000000 -0.684375 -0.767060
CO2 -0.127586  0.984981  0.957723 -0.684375  1.000000  0.912422
NOx -0.424782  0.967156  0.812078 -0.767060  0.912422  1.000000

In [31]:
y = df.tc.to_numpy()
x = df[["ne", "Me"]].to_numpy()
X = sm.add_constant(x)
print("y:\n", y, "\n\n X:\n", X, "\n")

Xt = X.transpose()
B = np.linalg.inv(Xt.dot(X))
print("B:", B, "\n")

a = np.dot(B.dot(Xt), y)
print("Параметры регрессии: a0:", a[0], "a1:", a[1], "\n")

y_r = X.dot(a)
print("Рассчетные значения y \n", y_r, "\n")

e = y - y_r
print("Остатки e \n", e)

y:
 [80.7 82.8 83.2 79.3 80.2 80.7 83.2 83.7 80.3 80.4 81.5 82.3 84.3 80.2
 80.7 82.1 83.1 85.  80.7 80.8 82.8 83.6]

 X:
 [[1.00e+00 1.20e+03 1.40e+02]
 [1.00e+00 1.20e+03 2.10e+02]
 [1.00e+00 1.20e+03 2.52e+02]
 [1.00e+00 1.40e+03 2.80e+01]
 [1.00e+00 1.40e+03 7.00e+01]
 [1.00e+00 1.40e+03 1.40e+02]
 [1.00e+00 1.40e+03 2.10e+02]
 [1.00e+00 1.40e+03 2.52e+02]
 [1.00e+00 1.60e+03 2.80e+01]
 [1.00e+00 1.60e+03 7.00e+01]
 [1.00e+00 1.60e+03 1.40e+02]
 [1.00e+00 1.60e+03 2.10e+02]
 [1.00e+00 1.60e+03 2.52e+02]
 [1.00e+00 1.80e+03 2.80e+01]
 [1.00e+00 1.80e+03 7.00e+01]
 [1.00e+00 1.80e+03 1.40e+02]
 [1.00e+00 1.80e+03 2.10e+02]
 [1.00e+00 1.80e+03 2.52e+02]
 [1.00e+00 2.00e+03 2.80e+01]
 [1.00e+00 2.00e+03 7.00e+01]
 [1.00e+00 2.00e+03 1.40e+02]
 [1.00e+00 2.00e+03 2.10e+02]]

B: [[ 2.31825787e+00 -1.22720430e-03 -2.00419051e-03]
 [-1.22720430e-03  7.06837052e-07  5.82570004e-07]
 [-2.00419051e-03  5.82570004e-07  7.41355527e-06]]

Параметры регрессии: a0: 76.17962961022461 a1: 0.0018434663089912304

Рассчетные значения y
 [81.05937798 82.39317238 83.19344902 79.2940002  80.09427684 81.42807124
 82.76186564 83.56214228 79.66269346 80.4629701  81.7967645  83.1305589
 83.93083554 80.03138673 80.83166337 82.16545777 83.49925216 84.2995288
 80.40007999 81.20035663 82.53415103 83.86794543]

Остатки e
 [-0.35937798  0.40682762  0.00655098  0.0059998   0.10572316 -0.72807124
  0.43813436  0.13785772  0.63730654 -0.0629701  -0.2967645  -0.8305589
  0.36916446  0.16861327 -0.13166337 -0.06545777 -0.39925216  0.7004712
  0.29992001 -0.40035663  0.26584897 -0.26794543]

In [32]:
y = df.tc
X = df[["ne", "Me"]]
X = sm.add_constant(X)
print("y:\n", y, "\n\n X:\n", X, "\n")
model = sm.OLS(y, X)
reg = model.fit()

print("Параметры регрессии:\n", reg.params, "\n")

a0 = reg.params["const"]
a1 = reg.params["ne"]
a2 = reg.params["Me"]

y_r = reg.fittedvalues
e = reg.resid

print("Расчетные (прогнозные) значения:\n", y_r)
print("Остатки:\n", e)

y:
 0     80.7
1     82.8
2     83.2
3     79.3
4     80.2
5     80.7
6     83.2
7     83.7
8     80.3
9     80.4
10    81.5
11    82.3
12    84.3
13    80.2
14    80.7
15    82.1
16    83.1
17    85.0
18    80.7
19    80.8
20    82.8
21    83.6
Name: tc, dtype: float64

 X:
     const    ne   Me
0     1.0  1200  140
1     1.0  1200  210
2     1.0  1200  252
3     1.0  1400   28
4     1.0  1400   70
5     1.0  1400  140
6     1.0  1400  210
7     1.0  1400  252
8     1.0  1600   28
9     1.0  1600   70
10    1.0  1600  140
11    1.0  1600  210
12    1.0  1600  252
13    1.0  1800   28
14    1.0  1800   70
15    1.0  1800  140
16    1.0  1800  210
17    1.0  1800  252
18    1.0  2000   28
19    1.0  2000   70
20    1.0  2000  140
21    1.0  2000  210

Параметры регрессии:
 const    76.179630
ne        0.001843
Me        0.019054
dtype: float64

Расчетные (прогнозные) значения:
 0     81.059378
1     82.393172
2     83.193449
3     79.294000
4     80.094277
5     81.428071
6     82.761866
7     83.562142
8     79.662693
9     80.462970
10    81.796765
11    83.130559
12    83.930836
13    80.031387
14    80.831663
15    82.165458
16    83.499252
17    84.299529
18    80.400080
19    81.200357
20    82.534151
21    83.867945
dtype: float64
Остатки:
 0    -0.359378
1     0.406828
2     0.006551
3     0.006000
4     0.105723
5    -0.728071
6     0.438134
7     0.137858
8     0.637307
9    -0.062970
10   -0.296765
11   -0.830559
12    0.369164
13    0.168613
14   -0.131663
15   -0.065458
16   -0.399252
17    0.700471
18    0.299920
19   -0.400357
20    0.265849
21   -0.267945
dtype: float64

In [33]:
print("Отчет по регрессии")
print("Тип объекта: ", type(reg))
print(reg.summary(), "\n\n")

print("t-статистика:\n", reg.tvalues, "\n\n")
print("Расчетное значение критерия Дарбина-Уотсона:\n", durbin_watson(reg.resid), "\n\n")
print("Первый коэффициент автокорреляции остатков:", reg.resid.autocorr(lag=1), "\n\n")

Отчет по регрессии
Тип объекта:  <class 'statsmodels.regression.linear_model.RegressionResultsWrapper'>
                            OLS Regression Results
==============================================================================
Dep. Variable:                     tc   R-squared:                       0.934
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     134.8
Date:                Tue, 10 Mar 2026   Prob (F-statistic):           5.96e-12
Time:                        21:03:10   Log-Likelihood:                -10.882
No. Observations:                  22   AIC:                             27.76
Df Residuals:                      19   BIC:                             31.04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         76.1796      0.650    117.176      0.000      74.819      77.540
ne             0.0018      0.000      5.135      0.000       0.001       0.003
Me             0.0191      0.001     16.389      0.000       0.017       0.021
==============================================================================
Omnibus:                        0.342   Durbin-Watson:                   2.383
Prob(Omnibus):                  0.843   Jarque-Bera (JB):                0.471
Skew:                          -0.235   Prob(JB):                        0.790
Kurtosis:                       2.458   Cond. No.                     1.17e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


t-статистика:
 const    117.176300
ne         5.135200
Me        16.389261
dtype: float64


Расчетное значение критерия Дарбина-Уотсона:
 2.3834773979496466


Первый коэффициент автокорреляции остатков: -0.229034889197773

In [34]:
alpha = 0.05
print("Уровень ошибки:", alpha,
    "Уровень значимости для двустороннего обратного распределения Стьюдента:", 1 - alpha / 2,
    "Уровень значимости для обратного F-распределения:", 1 - alpha
)

print("Число степеней свободы регрессии: ", reg.df_model)
print("Число степеней свободы остатков: ", reg.df_resid)

t_inv = stats.t.ppf(1 - alpha / 2, reg.df_resid)
print("Табличное значение критерия Стьюдента", t_inv)

F_inv = stats.f.ppf(1 - alpha, reg.df_model, reg.df_resid)
print("Табличное значение критерия Фишера", F_inv)

Уровень ошибки: 0.05 Уровень значимости для двустороннего обратного распределения Стьюдента: 0.975 Уровень значимости для обратного F-распределения: 0.95
Число степеней свободы регрессии:  2.0
Число степеней свободы остатков:  19.0
Табличное значение критерия Стьюдента 2.0930240544083087
Табличное значение критерия Фишера 3.5218932605788256

In [35]:
fig = go.Figure()

fig.add_trace(
    go.Scatter3d(
        x=df["ne"],
        y=df["Me"],
        z=df["tc"],
        mode="markers",
        name="исходные данные",
        marker=dict(
            color="rgba(0, 0, 255, 1)",
            size=7,
            opacity=0.8
        ),
        showlegend=True
    )
)

fig.add_trace(
    go.Scatter3d(
        x=df["ne"],
        y=df["Me"],
        z=y_r,
        mode="markers",
        name="лин. модель",
        marker=dict(
            color="rgba(0, 255, 0, 1)",
            size=7,
            opacity=0.8
        ),
        showlegend=True
    )
)

In [36]:
fig.update_layout(scene=dict(
    xaxis_title="ne, об/мин",
    yaxis_title="Me, Нм",
    zaxis_title="t, °C"),
    title_text="Температура в зависимости от частоты и крутящего момента",
    title_font_size=20,
    width=700,
    margin=dict(r=20, b=10, l=10, t=10)
)

fig.show()

In [37]:
x_pr = np.array([1, 1900, 250])
y_pr = reg.predict(x_pr)
print("Точечный прогноз: y =", y_pr[0], "\n")

Se = np.sqrt(reg.scale)

alpha = 0.01
t_inv = stats.t.ppf(1 - alpha / 2, reg.df_resid)
print("Табличное значение критерия Стьюдента", t_inv)

U = Se * t_inv * np.sqrt(1 + np.dot(x_pr.transpose(), B.dot(x_pr)))
print("Ширина доверительного интервала", U, "при уровне ошибки", alpha)
print("y = ", y_pr[0] - U, "...", y_pr[0] + U)

Точечный прогноз: y = 84.4457670238931

Табличное значение критерия Стьюдента 2.860934606464979
Ширина доверительного интервала 1.3499871127629601 при уровне ошибки 0.01
y =  83.09577991113014 ... 85.79575413665606

In [38]:
fig.add_trace(
    go.Scatter3d(
        x=[x_pr[1]],
        y=[x_pr[2]],
        z=[x_pr[0]],
        error_z=dict(
            type="data",
            array=[U],
            visible=True
        ),
        mode="markers",
        name="прогноз",
        marker=dict(
            color="rgba(255, 0, 0, 1)",
            size=7,
            opacity=0.8
        ),
        showlegend=True
    )
)

fig.update_layout(scene=dict(
    xaxis_title="ne, об/мин",
    yaxis_title="Me, Нм",
    zaxis_title="t, °C"),
    title_text="Температура в зависимости от частоты и крутящего момента",
    title_font_size=20,
    width=700,
    margin=dict(r=20, b=10, l=10, t=10)
)

fig.show()